### ISSUE TITLE
Incorrectly reloading extension

### ISSUE THREAD

**Issue by avi12** [extend-chrome/rollup-plugin-chrome-extension#85]
### Describe the bug
After the Rollup configurations re-run, `simplerReload()` doesn't reload the background page.

### How do we reproduce?
1. Have a background script.
1. Apply any modification that would trigger the Rollup configurations to re-run.
1. The extension will auto-reload, but inspecting the background page reveals an error of the form:
    ```
    background-page-reloader-2453c4f4.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
    ```

### Expected behavior
Reload the background page.

### Please complete the following information:

- Library Version:: 3.5.2
- Operating System: Windows 10 x64 21H1
- Browser: Google Chrome Canary 94.0.4584.0
- Node Version: 14.7.3

### Additional context
I realized that it has to do specifically with not reloading the background page because when manually reloading, the extension _does_ load as usual., rather than throw the same error.

**Comment by jacksteamdev** [comment]
Confirmed. This is an intermittent problem for me. My theory is that Chrome is trying to read the manifest before Rollup is done writing it, which would make it a Rollup bug, since the plugin hook `writeBundle` is supposed to run after all files have been written.

Relatedly, I've noticed an error saying that the manifest isn't valid (and Chrome disables the extension), which would fit in with the above theory.

@avi12 I'm [releasing a patch under beta](https://github.com/extend-chrome/rollup-plugin-chrome-extension/releases/tag/v3.6.0-0) to delay reload by 100 ms and see if that helps. You can configure the delay length like so:

```javascript
// default delay is 100ms
simpleReloader({ reloadDelay: 100 })
```

Let me know if this fixes the issue for you, and I'll release it under `main`!

**Comment by avi12** [comment]
Unfortunately, I need #86 to be resolved first so I can test this issue's fix
